export default {
    loginTitle: "LOGIN",
    passwordPlaceholder: 'password',
    loginButton: "Log In",
    orders: "Orders",
    account: "Your Account",
    logout: "Logout",
    planShow: "Schedule preview",
    addDisposition: "Add disposition",
    restaurantsInfo: "Information about restaurant",
    restaurants: "Restaurants",
    newEmployee: "Add new employee",
    actualOrders: "Current orders",
    allHistory: "Orders history",
    restaurantsCash: "Restaurant balance sheet",
    hall: "Hall",
    manageEmployees: "Manage employees",
    plan: "Graphic",
    yourOrders: "Your orders",
    accountEdit: "Edit your details",
    name: "Name",
    surname: "Surname",
    email: "Email",
    phone: "Phone number",
    close: "Close",
    save: "Save",
    loginError: "Incorrect password or login, please try again!",
    error: "Error!",
    accountEditError: "All fields must be completed!",
    accountEditSuccess: "Changes approved!",
    success: "Thank you!",
    passwordEdit: "Edit your password",
    password: "Password",
    repeatPassword: "Repeat password",
    passwordSuccess: "Password has been changed!",
    passwordError: "The password must have at least 6 characters and the passwords must be identical!",
    addDispositionTitle: "Adding a disposition",
    putDispositions: "Enter your dispositions...",
    send: "Send",
    dispositionSuccess: "New disposition has been added!",
    dispositionError: "The disposition must be completed",
    waitingTimeSuccess: "The waiting time has been set!",
    waitingTimeError: "Set waiting time!",
    showOrder: "Order preview",
    dish: "Dish",
    waitingTime: "Waiting time: ",
    minutes: "minutes",
    waitingTimeSet: "Set waiting time",
    additionalComments: "Additional comments to order:",
    noOrders: "No orders",
    addOrder: "Add order",
    profilInfo: "Information about your profile",
    employeeNumber: "Employee number",
    role: "Role",
    back: "Back",
    changePassword: "Change password",
    editData: "Edit data",
    tableNumber: "Table number",
    startTime: "Start time",
    starters: "Starters",
    soups: "Soups",
    mainDish: "Main Dishes",
    desserts: "Desserts",
    drinks: "Drinks",
    dishName: "Name",
    dishDescription: "Description",
    price: "Price",
    currency: "$",
    addOrderSuccess: "New order added!",
    addOrderError: "Dishes must be added to the order!",
    add: "Add",
    delete: "Delete",
    searchDish: "Search for the dish to add",
    addedDishes: "Added dishes",
    setOrder: "Submit your order",
    editOrder: "Edit order",
    restaurantInfo: "Information about restaurant",
    city: "City",
    address: "Address",
    manager: "Manager",
    employeeCount: "Number of employees",
    tablesCount: "Number of tables",
    numberOfSeats: "Number of seats",
    status: "Status",
    free: "Free",
    taken: "Taken",
    head: "Head",
    waiter: "Waiter",
    cook: "Cook",
    started: "Started",
    inProgress: "In progress",
    issued: "Issued",
    payed: "Payed",
    totalPrice: "Total price: ",
    nameAndSurnameWaiter: "Name and surname of the waiter accepting the order:",
    pay: "Pay",
    day: "Day",
    startHour: "Start time",
    endHour: "End time",
    sendedDisposition: "Dispositions given by you:",
    allYourOrders: "All your orders",
    endTime: "End time",
    date: "Date",
    addDayPlanTitle: "Add new date plan",
    addDayPlanSuccess: "A new plan has been added!",
    addDayPlanError: "All fields must be completed!",
    dayBalance: "Daily",
    monthBalance: "Monthly",
    yearBalance: "Yearly",
    allOrders: "All orders",
    cancelOrder: "Cancel",
    scheduleEditTitle: "Graphic management for individual days",
    sendedDispositionByEmployee: "Dispositions given by the employee",
    manage: "Manage",
    manageEmployeeSchedule: "Employee graphics management",
    employeeNumberD: "Employee number",
    actualGraphic: "Current schedule",
    manageEmployeeSchedules: "Manage employee schedule",
    noGraphic: "No schedule defined for the restaurant",
    addNewRestaurant: "Add new restaurant",
    info: "Information",
    edit: "Edit",
    restaurantList: "List of restaurants",
    addEmployeeSuccess: "New employee has been added!",
    addEmployeeTitle: "Enter the details of the new employee",
    addNewRestaurantSuccess: "New restaurant has been added!",
    addNewRestaurantError: "All items must be set before adding!",
    employees: "Employees",
    tables: "Tables",
    addressData: "Address data",
    create: "Create",
    addEmployee: "Add employee",
    firedEmployee: "Release the employee",
    manageEmployeesTitle: "Restaurant staff management",
    actaulEmployeesList: "Current employee list:",
    possibleEmployees: "Possible employees for employment:",
    pick: "Pick",
    manageManager: "Restaurant manager management",
    actualManager: "Current manager:",
    deleteTable: "Delete Table",
    manageTables: "Table management",
    actualTableList: "Current table list:",
    addNewTable: "Add new table",
    addTable: "Add table",
    editMenuSuccess:"The operation completed successfully!",
    editDish:"Edit dish",
    category:"Category",
    mainName:"Main dish",
    soupName:"Soup",
    dessertName:"Dessert",
    drinkName:"Drink",
    starterName:"Starter",
    editRestaurantSuccess: "The restaurant edition was successful!",
    saveAll:"Save all",
    showOrders:"Orders preview",
    addNewDish:"Add new dish",
    cashBalanceShow:"Viewing restaurant balance",
    editOrderSuccess:"Order has been changed",
    lack:"No disposition",
    forgotPasswordTitle:"Password reset",
    reset:"Reset",
    resetError:"The user with the e-mail address does not exist",
    resetSuccess:"Password reset! A new password has been sent to your email",
    remind: "Do not you remember the password ?"

}