export default {
    loginTitle: "LOGOWANIE",
    passwordPlaceholder: 'hasło',
    loginButton: "Zaloguj",
    orders: "Zamówienia",
    account: "Twoje Konto",
    logout: "Wyloguj",
    planShow: "Podgląd grafiku",
    addDisposition: "Dodaj dyspozycje",
    restaurantsInfo: "Informacje o restauracji",
    restaurants: "Restauracje",
    newEmployee: "Dodaj nowego pracownika",
    actualOrders: "Aktualne zamówienia",
    allHistory: "Historia zamówień",
    restaurantsCash: "Bilans restauracji",
    hall: "Sala",
    manageEmployees: "Zarządzaj pracownikami",
    plan: "Grafik",
    yourOrders: "Twoje zamówienia",
    accountEdit: "Edytuj swoje dane",
    name: "Imię",
    surname: "Nazwisko",
    email: "Adres email",
    phone: "Numer telefonu",
    close: "Wyjdź",
    save: "Zapisz",
    loginError: "Błędne hasło lub login, spróbuj ponownie!",
    error: "Błąd!",
    accountEditError:"Wszystkie pola muszą zostać uzupełnione!",
    accountEditSuccess:"Zatwierdzono zmiany!",
    success:"Dziękujemy!",
    passwordEdit:"Edytuj swoje hasło",
    password:"Hasło",
    repeatPassword:"Powtórz hasło",
    passwordSuccess:"Hasło zostało zmienione!",
    passwordError:"Hasło musi posiadać przynajmniej 6 znaków oraz wpisane hasła muszą być identyczne!",
    addDispositionTitle:"Dodawanie dyspozycji",
    putDispositions:"Wprowadź swoje dyspozycje...",
    send:"Prześlij",
    dispositionSuccess:"Dodano nową dyspozycje!",
    dispositionError:"Dyspozycja musi zostać uzupełniona!",
    waitingTimeSuccess:"Czas oczekiwania został ustawiony!",
    waitingTimeError:"Ustaw czas oczekiwania!",
    showOrder:"Podgląd zamówienia",
    dish:"Danie",
    waitingTime:"Czas oczekiwania: ",
    minutes:"minut",
    waitingTimeSet:"Ustaw czas oczekiwania",
    additionalComments:"Dodatkowe uwagi do zamówienia:",
    saveTime:"Zapisz czas",
    noOrders:"Brak zamówień",
    addOrder:"Dodaj zamówienie",
    profilInfo:"Informacje o Twoim profilu",
    employeeNumber:"Numer pracowniczy",
    role:"Stanowisko",
    back:"Powrót",
    changePassword:"Zmień hasło",
    editData:"Edytuj dane",
    tableNumber: "Numer stołu",
    startTime: "Czas rozpoczęcia",
    starters:"Przystawki",
    soups:"Zupy",
    mainDish:"Dania Główne",
    desserts:"Desery",
    drinks:"Napoje",
    dishName:"Nazwa",
    dishDescription:"Opis",
    price:"Cena",
    currency:"zł",
    addOrderSuccess:"Dodano nowe zamówienie!",
    addOrderError:"Do zamówienia muszą zostać dodane dania!",
    add:"Dodaj",
    delete:"Usuń",
    searchDish:"Wyszukaj danie do dodania",
    addedDishes:"Dodane dania",
    setOrder:"Złóż zamówienie",
    editOrder:"Edytuj zamówienie",
    restaurantInfo:"Informacje o restauracji",
    city:"Miasto",
    address:"Adres",
    manager:"Kierownik restauracji",
    employeeCount:"Liczba pracowników",
    tablesCount:"Liczba stolików",
    numberOfSeats:"Liczba miejsc",
    status:"Status",
    free:"Wolny",
    taken:"Zajęty",
    head:"Dyrektor",
    waiter:"Kelner",
    cook:"Kucharz",
    started:"Rozpoczęte",
    inProgress:"W trakcie",
    issued:"Zrealizowane",
    payed:"Opłacone",
    totalPrice:"Łączna cena: ",
    nameAndSurnameWaiter:"Imię i nazwisko kelnera przyjmującego zamówienie:",
    pay:"Opłać",
    day:"Dzień",
    startHour:"Godzina rozpoczęcia",
    endHour:"Godzina zakończenia",
    sendedDisposition:"Przekazane dyspozycje przez Ciebie:",
    allYourOrders:"Wszystkie Twoje zamówienia",
    endTime:"Czas zakończenia",
    date:"Data",
    addDayPlanTitle:"Dodaj nowy plan dnia",
    addDayPlanSuccess:"Dodano nowy plan!",
    addDayPlanError:"Wszystkie pola muszą być uzupełnione!",
    dayBalance:"Dzienny",
    monthBalance:"Miesięczny",
    yearBalance:"Roczny",
    allOrders:"Wszystkie zamówienia",
    cancelOrder:"Anuluj zamówienie",
    scheduleEditTitle:"Zarządzanie grafikami na poszczególne dni",
    sendedDispositionByEmployee:"Przekazane dyspozycje przez pracownika",
    manage:"Zarządzaj",
    manageEmployeeSchedule:"Zarządzanie grafikami pracowników",
    employeeNumberD:"Numer pracownika",
    actualGraphic:"Aktualny grafik",
    manageEmployeeSchedules:"Zarządzaj grafikiem pracowników",
    noGraphic:"Brak zdefiniowanego grafiku dla restauracji",
    addNewRestaurant:"Dodaj nową restaurację",
    info:"Informacje",
    edit:"Edytuj",
    restaurantList:"Lista restauracji",
    addEmployeeSuccess:"Dodano nowego pracownika!",
    addEmployeeTitle:"Wprowadź dane nowego pracownika",
    addNewRestaurantSuccess:"Dodano nową restaurację!",
    addNewRestaurantError:"Wszystkie rzeczy muszą być ustawione przed dodaniem!",
    employees:"Pracownicy",
    tables:"Stoły",
    addressData:"Dane adresowe",
    create:"Utwórz",
    addEmployee:"Dodaj pracownika",
    firedEmployee:"Zwolnij pracownika",
    manageEmployeesTitle:"Zarządzanie pracownikami restauracji",
    actaulEmployeesList:"Aktualna lista pracowników:",
    possibleEmployees:"Możliwi pracownicy do zatrudnienia:",
    pick:"Wybierz",
    manageManager:"Zarządzanie kierownikiem restauracji",
    actualManager:"Aktualny kierownik:",
    deleteTable:"Usuń Stół",
    manageTables:"Zarządzanie stołami",
    actualTableList:"Aktualna lista stołów:",
    addNewTable:"Dodaj nowy stół",
    addTable:"Dodaj stół",
    editMenuSuccess:"Operacja zakończyła się pomyślnie!",
    editDish:"Edytuj Danie",
    category:"Kategoria",
    mainName:"Danie główne",
    soupName:"Zupa",
    dessertName:"Deser",
    drinkName:"Napój",
    starterName:"Przystawka",
    editRestaurantSuccess:"Edycja restauracji przebiegła pomyślnie!",
    saveAll:"Zapisz wszystko",
    showOrders:"Podgląd zamówień",
    addNewDish:"Dodaj nowe danie",
    cashBalanceShow:"Podgląd bilansu restauracji",
    editOrderSuccess:"Zamówienie zostało zmodyfikowane",
    lack:"Brak",
    forgotPasswordTitle:"Resetowanie hasła",
    reset:"Resetuj",
    resetError:"Użytkownik o podanym mailu nie istnieje",
    resetSuccess:"Hasło zresetowane! Nowe hasło zostało wysłane na Twój email",
    remind:"Nie pamiętasz hasła ?"


}